print('Desafio 018 - Python - Curso em Video')
import math
print('Vamos descobrir o Seno, Cosseno e Tangente do Ângulo!')
a = float(input('Qual o ângulo? '))
seno = math.sin(math.radians(a))
coss = math.cos(math.radians(a))
tang = math.tan(math.radians(a))
print('O ângulo de {:.1f} tem o SENO de {:.2f}.'.format(a, seno))
print('O ângulo de {:.1f} tem o COSSENO de {:.2f}.'.format(a, coss))
print('O ângulo de {:.1f} tem o TANGENTE de {:.2f}.'.format(a, tang))
