nome = input('Qual o seu nome? ')
print('')
print('Seu nome com todas as letras maiúsculas é: ')
print(nome.upper())
print('')
print('Seu nome com todas as letras menúsculas é: ')
print(nome.lower())
print('')
divi = nome.split()
junto = ''.join(divi)
print('Seu nome tem {} letras.'.format(len(junto)))
print('')
print('Seu primeiro nome tem {} letras.'.format(len(divi[0])))
